### ISSUE TITLE
GTEx_samples-track.tsv

### ISSUE THREAD

**Issue by ANiknejad** [BgeeDB/expression-annotations#108]
the most important file to follow-up GTEx sample processing by our team.

QUESTIONS:

8335 samples are YES for column B (Included in Bgee Annotation (YES/NO)), while at the beginning of the annotation work we were talking on 6'000 samples to annotate?
(Among these 8335 samples, 510 are Affy so we can talk on 7825, still not 6'000????

**Comment by ANiknejad** [comment]
@mimiblis 
Angélique, on ne parle pas là des derniers tris au sujet des chip types, juste des samples retenus pour l'annotation au début,

**Comment by mimiblis** [comment]
- because at the beginning we were more stringend --> now BMI ok <35 and before it was ok <25...
- in track-file I think there are redundancies
- I am checking it all now, this file, so I will tell you, if I see weird things

**Comment by ANiknejad** [comment]
>in track-file I think there are redundancies

NO, the number of lines is identical to the original number of GTEx samples: 11'983!

**Comment by mimiblis** [comment]
we may have to refer to @aechchiki 's google doc, were she detaily explains how we did the annotation ?

**Comment by ANiknejad** [comment]
won't explain why the number is different anyway...

**Comment by mimiblis** [comment]
well then I just remember the few things I cited, but there should be others like it (@aechchiki do you have some souvenir from that?)

**Comment by ANiknejad** [comment]
GTEX_selected-samples_annots.tsv
has 8256 samples

This number should match the number of
YES for column B (Included in Bgee Annotation (YES/NO))
in GTEx_samples-track.tsv

**Comment by mimiblis** [comment]
franchement, je dois dire que j'en sais rien, ce n'était pas moi qui avait créé ces fichiers, je ne sais pas s'ils ont été mis à jour au fur et a mesure de nos décisions...

**Comment by aechchiki** [comment]
I'm gonna check this.

**Comment by mimiblis** [comment]
@ANiknejad : il est clair que quand je vais faire le mapping UBERON et SRX dans le fichier track que je vais bien mieux voir les problèmes qui se posent (peut-etre) encore sur le track-file... 
Avant de tirer des conclusion, il faut que je fasse ça, et ainsi on aura  peut etre une meilleure vue. (dici fin de la semaine sera ok)

**Comment by ANiknejad** [comment]
ok, merci angélique

**Comment by mimiblis** [comment]
:-)

**Comment by ANiknejad** [comment]
>mais a-t-on besoin du selected sample si toutes les infos sont dans track.tsv?

clairement, non, mais il faut qu'au final le nombre de samples qui seront 'YES+ chip type = RNA_seq'
dans le GTEx_samples-track.tsv corresponde au nombre de GTEx annotation dans RNASeqLibrary.tsv

**Comment by mimiblis** [comment]
oui bien entendu :-)

**Comment by mimiblis** [comment]
#counting samples --> ne pas s'effrayer, le mapping uberon pas encore fait, donc ne tirons pas encore de conclusions...
* Affymetrix Data with status YES:
  - in affyGTEX.tsv = 423 samples <--> in track-file: 510 samples (affymetrix expression)

* Illumina Exome Data with status YES:
  - in exome.tsv = 117 samples <--> in track-file = 119 samples(Illumina Human Exome SNP Array)

* Illumina OMNI Data with status YES:
  - in OMNI.tsv = 328 samples <--> in track-file = 330 samples (Illumina OMNI SNP Array)

*TrueSeq.v1 (without being RNAseq, without SRR nor SRX) --> 3 samples

* RNAseq Data with Status YES:
  - in RNAseqLibrary.tsv = 4946 samples <--> in track-file = 6875 samples

* WGS = 106 samples
* WGX = 387 samples

**Comment by mimiblis** [comment]
- I am currently (in the coming days), reporting the UBERON mapping in the track-file
- I am also exctracting the GTEx ID's with status YES, but not present in any annotation file --> after this extraction I might be capable of telling what is going on

**Comment by mimiblis** [comment]
@ANiknejad and @aechchiki : please have a look in /expression-annotations/annotations/gtex/statusYES_notAnnotated.tsv
- this file provides the list of GTEx ID's (all assay confounded) that are annotated as YES in track-file, but that were not annotated by BGEE.
- bon, I know that I was the only annotater (so you might blame me) --> but it means I forgot 2102 samples?? --> I assure you, I do not take drugs

**Comment by fbastian** [comment]
This looks like a terrible mess :/ Could @ANiknejad and @mimiblis try to skype @aechchiki to double check everything with her?

**Comment by mimiblis** [comment]
I already discussed with her. I now know what the problem is --> do not worry to much
just need @ANiknejad to aprove my decision, but it's better if we could speak instead of writing --> more understandable, and less panic

**Comment by ANiknejad** [comment]
no panic but...
>!!!so @ANiknejad I think we should trust as much as possible selected-samples file 
I remember you that this file is not clean so far! see #77 

(not available for skype today, sorry)

**Comment by mimiblis** [comment]
no problem, anytime Anne, if oyu see me online, you can contact me ;-)

**Comment by mimiblis** [comment]
1. remove tumoral samples 
*11983-127 = 11856

2. remove samples coming from NO subjects
*155 subjects with status NO (3303-127 = 3176 samples status NO)
*11856-3176 = 8680

3. remove samples coming from PENDING subjects
*183 subjects with status PENDING (309 samples status NO)
*8680-309 = 8371

4. in total : 
*3176+127+309 = 3612 removed samples, with status NO
*11983-3612 = 8371 kept samples, with status YES

5. it means and here is the source of our troubles:
*in selected-samples, there should be 8371 samples, and there is 8256 --> 115 samples missing in the file
*in selected samples, there are 6426 samples annotated as GOOD (corresponding to YES in track-sample) --> in track-file there are to much YES samples
*in selected-samples, there are 1659 samples annotated as BAD (corresonding to NO in track-file)
*in selected-samples, there are 156 samples that are not annotated
########
6. what to do now?
*redo the scripts to redo the selected samples file --> maybe the mistake comes from here
*if the mistake is not here, then it might be that we removed subjects, without updating subjects-track nore sample-track... thus now it's bullshit in selected-sample and in track-file
*since I have done all annotations, it will be "quick" for me to fly over all subjects or samples if needed... but hopefully we do not need to go there

**Comment by mimiblis** [comment]
1. remove tumoral samples 
*11983-127 = 11856

2. remove samples coming from NO subjects
*155 subjects with status NO (3303-127 = 3176 samples status NO)
*11856-3176 = 8680

3. remove samples coming from PENDING subjects
*183 subjects with status PENDING (309 samples status NO)
*8680-309 = 8371

4. in total : 
*3176+127+309 = 3612 removed samples, with status NO
*11983-3612 = 8371 kept samples, with status YES

5. it means and here is the source of our troubles:
*in selected-samples, there should be 8371 samples, and there is 8256 --> 115 samples missing in the file
*in selected samples, there are 6426 samples annotated as GOOD (corresponding to YES in track-sample) --> in track-file there are to much YES samples
*in selected-samples, there are 1659 samples annotated as BAD (corresonding to NO in track-file)
*in selected-samples, there are 156 samples that are not annotated

6. I found out that there are 2102 samples annotated as BAD in selected-samples that have a YES in track-file

--> put status NO in track file for these samples

7. it means now that we have 3612+2102 removed samples, with status NO = 5714 NO in track-file

8. it means now that we have 8371-2012 kept samples, with status YES = 6269 YES in track-file

**Comment by mimiblis** [comment]
--> put status NO in track file for these samples
@ANiknejad, @fbastian 
it's not done yet, but I already spent 10hours between yesterday and today, and frankly I am really tired of correcting these things... we should have gone really slower, thus not having these stupid stuff now. 
I will do it, I promise, just you might have to wait. I have to find a way to easily clean selected-samples and then to correct the track-file... --> of course python, but need to think deeply, not to manage any mistake, so that the end result is satisfying ;-)
I REALLY hope that there were just "stupid" mistakes (for example, one script did not take into account all samples), and that redo it will clean that.
Else it means there is problem with the annotation, and there... NO let's not think about the worse...

**Comment by ANiknejad** [comment]
I can see that you did a lot of job to check all these discrepancy. Thank you Angélique, and yes, we need clear explanations and clear count of samples at the end. I am confident into the annotation itself (UBERON mapping) for the samples we checked and annotated so far, but hope we did not miss samples.

**Comment by ANiknejad** [comment]
closed so far, on going review_of_GTEx_annotations_FILES by Amina
