### ISSUE TITLE
GSE43520: (suspect) annotation mistake (from source?)

### ISSUE THREAD

**Issue by aechchiki** [BgeeDB/expression-annotations#51]
Sample GSM1196043 from dataset GSE43520 was annotated: placenta, male, adult human stage. Seems weird to me. 
(Similar suspect error was already reported by ANN for sample GSM1064844, same dataset)

**Comment by ANiknejad** [comment]
well spotted, indeed, and this experiment is an important one (Kaessmann group, CIG).
But the issue is related to issue #42.
So far, yes, it should be annotated on the 'host' (=the mother) so without information about the sex of the embryo (here male embryo). Could you review and correct, please? Many thanks!

**Comment by aechchiki** [comment]
Done: 2dd7828d0c02a4325826d318d368531d65aedeb9

**Comment by ANiknejad** [comment]
I am sorry, Amina....i thought, the placenta was annotated on embryo stage instead of mother stage, but in fact it was already correctly 'adult stage'. So we can keep the information 'male' embryo just as an information, currently not included in the pipeline.
Could you revert...?
Sorry again!
(just do the revert if you exactly know how to process, please!)

**Comment by aechchiki** [comment]
Done :) 920643b8a55f8de17d96befcdcb90240b08ddd10

**Comment by ANiknejad** [comment]
Sorry again, and many thanks!

**Comment by ANiknejad** [comment]
Hi Amina,

could you please add and annote these samples too?
GSM1196058
GSM1196059
GSM1196060

(not necessary to edite RNASeqExperiment.tsv : it was already 'Total', 52/52 samples were annotated, now there are 55 samples available....)

**Comment by aechchiki** [comment]
(partially) done: 3bc3893a71c3475ef193a2aad1d8c5d4065d026f (stage, strain, sex, taxon )
However, cannot find organ info for samples (not GEO nor paper)....

**Comment by ANiknejad** [comment]
done in #68
