### ISSUE TITLE
Gtex normality - cause of death and certain diseases

### ISSUE THREAD

**Issue by mimiblis** [BgeeDB/expression-annotations#55]
This issue is to clarify certain cause of death and to see whether "touched" organs can be used for annotations or not:

- cardiac arrest or myocardial infarction: I would have eliminated the heart, but this does not mean the heart was sick (mostly coronar vessel problems) --> so for now pending
- AVC: yes eventhough the brain was probably "filled" with blood, I do not think this makes the brain as a non-usable organ. This is not like tumour or such.
- gunshot wound in the back: nothing special specified, but: since the GSW was lethal, organs were certainly touched...
- same for multiple injuries by blunt object (knife)
- anoxia by respiratory failures: hanging ok because it is brutal, but what about pulmonary function disorder? --> it is not always precised if the lung were sick (asthma, pneumonia...)
- unknown cause of death: heummmm, mostly these poeple died home,  and there is no cause of death (assumed cardio-pulm deffect) --> any organ to keep out?
- liver failure, DTHHRDY of 0 --> keep out liver? (it is not specified what failure)
- atherosclerosis : exlud vessels?

- no cause of death but diseases: how should we consider them? for now I just took these poeple out, because they are few:
	- lupus
	- sarcoidosis
	- diabetis

- other kind of diseases, that influence less the organs if we can say:
	- anemia (exclud blood?)
   - epilepsy (exclud brain?)

**Comment by fbastian** [comment]
* Hardy scale: not enough to discard a patient, e.g., a patient dead from dementia can be classified as Hardy Scale code 4.
* cardiac arrest or myocardial infarction: if not disease, keep it (we all die from cardiac arrest...); check other information...
* AVC + Hardy scale 2 to 4: discard brain, keep other organs
* AVC + Hardy scale 0 or 1: keep all
* gunshot wound: keep all
* same for multiple injuries by blunt object (knife): keep all
* anoxia: depends on other info: it is OK if hanging is the cause of death, it is not if it is a disease. 
* unknown cause of death => keep all
* liver failure, DTHHRDY of 0 => pending
* atherosclerosis : exclude vessels
* lupus, sarco..., diabetis, anemia, epilepsy: given the low number of patients, discard all. Maybe keep if not enough patient.

**Comment by aechchiki** [comment]
New "normality issues", following discussion with @mimiblis:

- Heart Attack and Respiratory Failure: should we have the same precision (if available) on the Hardy Death Scale as we did for the CVA? In this case: 
    - Heart Attack - DTHHRDY=0,1, 2: don't discard heart tissue
    - Heart Attack - DTHHRDY=3, 4: discard heart tissue (same as "heart disease status")
    - Respiratory Failure - DTHHRDY=0,1, 2: don't discard lungs and related respiratory organs tissue
    - Respiratory Failure - DTHHRDY=3, 4: discard lungs and related respiratory organs tissue (same as "Chronic Respiratory Disease")
- schizophrenia, dementia, alzheimer: should we discard brain tissue?
- asthma: if the person didn't die because of respiratory failure, should we discard respiratory organs tissues?
- ascites ( causes abdominal distension, due to liquid accumulation in the peritoneal cavity, mainly due to liver failure - see: https://en.wikipedia.org/wiki/Ascites ); should we discard liver tissue?
- sexual-transmitted diseases (no additional details): should we discard the affected individuals?
- bacterial/fungal infection (no additional details): should we discard the affected individuals?
- disgnosis of cancer/non-metastatic cancer in the last 5-years previous to death (no additional details): should we discard the affected individuals?
- seizure: same as epilepsy... as we already determined, we discard them.
