### ISSUE TITLE
GTEx_annot_non-tumoral.tsv --> GOOD, BAD or PENDING (SMPTHNTS)

### ISSUE THREAD

**Issue by mimiblis** [BgeeDB/expression-annotations#70]
1. I would put GOOD, when the tissue is 90% the pointed one, with little residual of fat --> yes, no?
  - we also have to determine a threshold ASAP of what is acceptable, to already put BAD and GOOD instead of PENDING (due to large number of ssamples)
2. when only 1/6 piece is "contaminated" with fat or smthg I would put GOOD --> yes, no?
  - we have to put a threshold if we put yes, because it often comes that 3/6 pieces are contaminated
3. what to do with samples where they seem to have dissected 2 or more tissues
  - "normal" sample contain only one tissue for example COLON musuclaris or mucosa
  - but some are: COLON muscularis + mucosa in one sample AND sometimes muscularis is autolyzed but not mucosa, sometimes mucusa well preserved and not muscularis...
4. what to do with layers that are "slightly slought"?
5. what to do when there is no info: 
  - 6pieces. or 1 piece. --> annotated as GOOD, because there is nothing specified and we would lose a lot... (@aechchiki are you same advice?) --> d9e53f0
6. 6 pieces  ~9x3mm, all muscularis, ''presumed switch with 0825'' --> what to do with a presumed switch?

**Comment by mimiblis** [comment]
2 pieces; esophageal mucosa NOT prostate --> ???

**Comment by aechchiki** [comment]
@mimiblis, I think we should put "good" to every sample which is <10% "contamined" with other tissues: I say that because in one of my samples, I found the textual description "minimal contamination (~10%), good specimen".... I guess we should at least accept as "good" contaminations (at least up to) 10% threshold. 

-> also, do you think that holes or "badly cut" tissues could affect RNA analysis? :/

**Comment by mimiblis** [comment]
Ok for less than 10%
I do not think that "histologie " problems influence rnaseq. I had even "coloration problem" --> for me good samples

**Comment by mimiblis** [comment]
have done 3000 samples in 12 hours, impossible for me to finish until the end.
I am currently finishing muscle, and tomorrow I will do other organs until "skin" (not included)

**Comment by aechchiki** [comment]
Asking for opinion: if source reports "delineated" portion of contamination tissue (ex: "delineated" piece of fat on a portion of adrenal tissue), does it mean that the delineated piece was cut off the sample before RNA analysis, or does it just mean that they are aware that there's some contamination but it was not cut off the sample? Because it seems to me that the sampled pieces are very tiny (mm2)...so I am wondering if it is possible to cut off a contamination post-sampling.

**Comment by mimiblis** [comment]
From what I understood,  its histologically speaking  (under the microscope they delineated the bad area). 
I dont think they'vé cut after that. Otherwise they would have kept only 'perfect' samples

**Comment by aechchiki** [comment]
Ok, thanks @mimiblis  :)
Asking for another opinion: I believe that sample composition (eg,  piece of fat on adrenal tissue) shouldn't be a criterion to put a sample under "pending", because this is "just" a matter of annotation (check accepted % with Anne)....instead, it would be interesting to note if some kind of abnormality (eg, hyperplasia/disease/necrosis, etc ) has been reported. Do you agree? I mean, a sample containing  mixture of tissues can still be a "good specimen"... (just, we need to define a treshold to see what % of contamination should be acceptable to avoid annotation issues). 
ps: i agree that "fixation issues" (or other histological issue due to sample preparation) do not interfere with RNA quality, thus we don't care

**Comment by mimiblis** [comment]
When thé sample was well labeled (10% fat in muscle), I put ok.
But when I have more than two tissus mixed,  where each 'foreign'  tissu is more than 10% of sample I put bad. Also put bad when they say muscle+fat+tendon without more infos.
I have reported 'illnesses ' of tissus such as nécroses,  bronchitis atrophy. .. And put bad because it means unhealthy tissue. 
Voila

**Comment by aechchiki** [comment]
Yep, that was my question. 

But I was wondering, we shouldn't be mixing the concept of "good quality sample" and "pure sample". A good quality sample could include mixed tissues, each of them of good quality; and a bad quality sample could include a pure (but, for example necrotic, tissue). That's why we need two levels of precision: quality and purity.

We will need to discuss about this on Monday I guess.

**Comment by mimiblis** [comment]
Thé problem is that we would then need to see how to annotated these kind of mixture.  Then for example myocarde + pericard =/ Uberon left ventricle  (as they annotate)... 
Yop to discuss on Monday

**Comment by mimiblis** [comment]
Do we consider "menopausa" as abnormal tissues? then ovaries, vagina and such changes after it...

**Comment by aechchiki** [comment]
For menopausa, I guess "it's part of the natural variation" :)

**Comment by mimiblis** [comment]
But rnaseq young ovary and memopaused ovary wont be thé same. This is why I am à bit worried. I would séparate the two cases... but personal opinion haha

**Comment by mimiblis** [comment]
!!!!!!!!!! PITUITARY!!!!!!!!!!! --> UBERON terms need to be done manually, because they have not always annotated to the right "part" of the pituitary (adenohypophysis, mid part and neurohypophysis"

**Comment by ANiknejad** [comment]
we currently do not consider physiological status in our annotations (ex: pregnancy, menopausa,..), but please reported it in the comments column for now (as for 'sex' and 'strain', this information will probably be considered latter in Bgee)

**Comment by ANiknejad** [comment]
column I (SMPTHNTS), please remember that this is free text comments from different experimenters, so many discrepancy....I do not think we have to consider all the comments here

**Comment by mimiblis** [comment]
what shouldn't we consider for example? I considered a sample as bad when it was not healthy (eg prostatitis) or when the sample in question was not the one (eg skeletal muscle but the sample is 80% adipose).

**Comment by ANiknejad** [comment]
sorry not being clear, I was answering to 
--> we shouldn't be mixing the concept of "good quality sample" and "pure sample"

and also have a look at this comment here:
1 piece, adipose tissue (not pancreas as initially designated)

Means, somebody else first designated the tissue before final comments?
That can also explain this kind of comment.
2 pieces; esophageal mucosa NOT prostate

**Comment by ANiknejad** [comment]
for 'colon' annotation, please have a look at #57 and https://github.com/obophenotype/uberon/issues/1162

**Comment by mimiblis** [comment]
nice: I had a question about until what precision of UBERON was going 
Thank you

**Comment by ANiknejad** [comment]
Did you check column SMAFRZE?
'Use me' samples, Samples included in the GTEx Analysis Freeze</description><comment>Generated at LDACC

**Comment by ANiknejad** [comment]
for samples annotation, the link sent by Fred
http://www.ncbi.nlm.nih.gov/projects/gap/cgi-bin/document.cgi?study_id=phs000424.v6.p1&phd=3910#sec2.1

is very useful, see Aqua Kit, we see that there are instructions to take samples at a specific area, depending on surgical or post-mortem act

**Comment by mimiblis** [comment]
do we make a difference between sun exposed and not sun exposed skin?

**Comment by fbastian** [comment]
I think not, I think there are no such terms in Uberon, right?

**Comment by mimiblis** [comment]
Nô there are not such terms. But I was not sûre if maybe one would be adding terms like this

**Comment by fbastian** [comment]
No, this is a biological status or phenotype, not an anatomical structure.

**Comment by ANiknejad** [comment]
close and refer to #71 for description of sample check
