### ISSUE TITLE
GTEx-sample-annotations, where are we, what is still to do

### ISSUE THREAD

**Issue by mimiblis** [BgeeDB/expression-annotations#75]
Angelique:
- gone through all my organs except:
  - oesophagus for UBERON terms (waiting for #74)

**Comment by aechchiki** [comment]
Amina:
- discarded samples from all subjects annotated as "NO"
- conditionally discarded samples from all subjects annotated as "PENDING", refer to GTEx_subject_annots.tsv (`< sed -i '/pending_subject_GTEX.*sample_to_discard/d' >` )

**Comment by mimiblis** [comment]
Hi @aechchiki ,
Est-ce qu'il y a eu un soucis avec le fichier "selected" --> car je n'avais pas annoté un sample de skin of leg et d' eosophagus car ils sont tout seul tout en bas du fichier. du coup jte fais un screen shot, en fait je n'ai que l'organe : 
![capture du 2015-11-11 08 55 36](https://cloud.githubusercontent.com/assets/13200045/11086501/0672db44-8852-11e5-948b-c133816d0f2f.png)

**Comment by mimiblis** [comment]
état au 11.11.15: --> reste encore:
- eosophagus, gastroesophagus junction --> UBERON
- adipose tissue --> UBERON + sampling (some are still PENDING)
- coronary artery --> all PENDING (as well for sampling as for UBERON)
- aorta --> PENDING in UBERON
+ les deux dernières lignes toutes seules cf comment en dessus

**Comment by ANiknejad** [comment]
Precision estimation for Uberon mapping (GOOD/BAD)

I do not agree with some GOOD ones, 
for example, 
Blood	Whole Blood
has to be annotated on 
UBERON:0000178
name: blood

Gastrocnemius below patella
? what allows to map on ?
11907	gastrocnemius medialis 
instead of 
UBERON:0001388 gastrocnemius

**Comment by ANiknejad** [comment]
1270547	GTEX-13S7M-2226-SM-5S2WB	2 pieces; large calcified atheromatous plaque; well trimmed	Left	Blood Vessel	Artery - Coronary		1621	coronary artery 	GOOD	no significant plaques

--> to reject due to large calcified atheromatous plaque !!!!

**Comment by mimiblis** [comment]
Taking good notes for gastrocnemius. 
Weird for the artery with the plaques. I have to check this again moreover why I have put no signifiant plaque

**Comment by ANiknejad** [comment]
let's say, you agree with GTEx mapping when you put GOOD in column L 'precision estimation for Uberon mapping' 
and any modification from the original mapping is tracked by BAD or PENDING, right?
BAD you are confident in your proposition for another Uberon term
PENDING you need check from my part for modification
Is that correct?

**Comment by ANiknejad** [comment]
caution
UBERON:0002469Â ! Oesophagus mucosa

some typo to correct

**Comment by ANiknejad** [comment]
BIG error from GTEx
http://www.ncbi.nlm.nih.gov/projects/gap/cgi-bin/document.cgi?study_id=phs000424.v6.p1&phd=3910#sec2.1

Brain - cerebellum	Right cerebral frontal pole;

there is no frontal pole in the cerebellum, there is in the CEREBRUM (=cerebral hemisphere)

@fbastian 
something that needs contact with GTEx










UBERON:0001869
name: cerebral hemisphere

**Comment by mimiblis** [comment]
Because I then corrected on thé mapping after checking thé uberon issue #74. 
I can eliminate thé "not sûre part".  Was just to keep à trace of it.

**Comment by ANiknejad** [comment]
914542	GTEX-QMR6-1326-SM-32PLB	4   ~6x5mm aliquots	Cerebral frontal pole -right	Brain	Brain - Cerebellum		2037	cerebellum 

this is an error!
if the tissue is Cerebral frontal pole -right
it has to be annotated on 
UBERON:0002810
name: right frontal lobe
namespace: uberon
def: "A frontal cortex that is part of a right cerebral hemisphere."

(note that the term 'pole' is more precise than 'lobe', so for sake of security, I would prefer on 'lobe')
UBERON:0002795
name: frontal pole
namespace: uberon
def: "Component of the frontal lobe. The rostral and caudal boundaries of the frontal pole are the superior frontal gyrus and the rostral division of the middle frontal gyrus respectively (Christine Fennama-Notestine)." [NIFSTD:birnlex_1716

**Comment by ANiknejad** [comment]
Pathologists sound to have correct themselves by reporting tissues either as 'Cerebral frontal pole -right'
OR as 'cerebellum' but then the GTEx mapping is for both on 
2037	cerebellum 

914542	GTEX-QMR6-1326-SM-32PLB	4   ~6x5mm aliquots	Cerebral frontal pole -right	Brain	Brain - Cerebellum		2037	cerebellum

**Comment by mimiblis** [comment]
But we should wait for an answer from gtex team , before annotating right?

**Comment by ANiknejad** [comment]
no, I guess, we will follow the information reported by the pathologists:
- Right Cerebellum  ---> to annotate on UBERON:0014890 - right hemisphere of cerebellum
- cerebellum  ---> to annotate on UBERON:0002037 cerebellum
- Cerebral frontal pole -right  ---> UBERON:0002810 right frontal lobe

**Comment by mimiblis** [comment]
Ok

**Comment by ANiknejad** [comment]
860572	GTEX-RNOR-2326-SM-2TWC7	4 pieces up to 5x5 mm;	Cerebral frontal pole -right	Brain	Brain - Cortex		1870	frontal cortex 

to annotate on
UBERON:0002810
name: right frontal lobe
namespace: uberon
def: "A frontal cortex that is part of a right cerebral hemisphere." [OBOL:automatic]

**Comment by ANiknejad** [comment]
1271436	GTEX-14ICL-1826-SM-5RQIY	2 pieces, no significant atherosis, clean specimens	Femoral	Blood Vessel	Artery - Tibial	Left. Expected time lapse of greater than 20 mins for tissue removal is due to GTEx recovery workflow."	7610	tibial artery 

to annotate on UBERON:0002060
name: femoral artery
(tagged as BAD Uberon precision but empty Uberon term in the file)

**Comment by ANiknejad** [comment]
GTEX-PLZ6-0726-SM-3P619	2, ~ 10x8 mm pieces,<1%  fat; focal fixation fractures	Anterior	Pancreas	Pancreas	Anterior Mid Portion	1150	body of pancreas 

Please conserve the GTEx annotation on 'body of pancreas', because the anterior surface of the pancreas belongs to the body, 
see
https://en.wikipedia.org/wiki/Pancreas

**Comment by ANiknejad** [comment]
UBERON:0001161
name: body of stomach
namespace: uberon
def: "The body of stomach is the part of the stomach that lies between the fundus above and the pyloric antrum below; **its boundaries are poorly defined**[GO]." [GO:0014845, http://en.wikipedia.org/wiki/Body_of_stomach]

So I am not sure I would correct GTEx from 945	stomach

**Comment by ANiknejad** [comment]
I would reject (= put BAD samples) the 2 following:
860471	GTEX-R55F-1326-SM-2TWBM	4 pieces up to 6x5 mm; two pieces with focal artifacts and bone fragments	Cerebral frontal pole -right	Brain	Brain - Cortex		1870	frontal cortex 	GOOD	no info	GOOD	bone fragments
860470	GTEX-R55F-1326-SM-2TF5F	4 pieces up to 6x5 mm; two pieces with focal artifacts and bone fragments	Cerebral frontal pole -right	Brain	Brain - Cortex		1870	frontal cortex 	GOOD	no info	GOOD	bone fragments

**Comment by ANiknejad** [comment]
I am not sure we can annotate (all?) 
Anterior left ventricle	Heart  Heart - Left Ventricle		
on
6566	left ventricle myocardium 

because some samples contain *papillary muscles* that are not part of the myocardium:

914955	GTEX-U3ZN-1426-SM-3DB87	2 pieces 9x7 & 7x6 mm; good clean specimen; papillary muscles with endothelium

see 
http://www.healthbanks.com/practicecollateral/cardiology/ccsf/v1i2/2.htm

The target defined by GTEx
http://www.ncbi.nlm.nih.gov/projects/gap/cgi-bin/document.cgi?study_id=phs000424.v6.p1&phd=3910#sec2.1

is

Heart	Anterior left ventricle;

So maybe **safer** to annotate on 
UBERON:0002084
name: heart left ventricle

**Comment by ANiknejad** [comment]
**GTEx
Tissue Harvesting Work Instruction**

http://biospecimens.cancer.gov/resources/sops/docs/GTEx_SOPs/BBRB-PR-0004-W1%20GTEx%20Tissue%20Harvesting%20Work%20Instruction.pdf

see that they sample 'minor salivary glands'

**Comment by mimiblis** [comment]
@ANiknejad : need you to look at UBERON status and terms for the following samples (in selected-samples file)
- 1109343
- from 1273751 --> all gastroesophagal junction --> if their UBERON is ok or not
- 931657 (I will then correct all pending for that organ)
- 1272314 (I will then correct all pending for that organ)
- 931676 --> all UBERON annotation about aorta

**Comment by ANiknejad** [comment]
COMMENTS below:

@ANiknejad : need you to look at UBERON status and terms for the following samples (in selected-samples file)

1109343
 ----> ANN: ok, UBERON:0000002 name: uterine cervix

from 1273751 --> all gastroesophagal junction --> if their UBERON is ok or not
---> ANN:
"Muscularis of  lowest portion of esophagus"	"Esophagus"	"Esophagus - Gastroesophageal Junction"		4550	"gastroesophageal sphincter "
on garde l'annotation comme ca pour le moment mais ça peut changer si Chris répond cf https://github.com/obophenotype/uberon/issues/1182
(UBERON:0035833+name: lower esophagus muscularis layer  c'est pour la partie juste au-dessus du gastroesophageal, donc non approprié)

1272314 (I will then correct all pending for that organ)
-->ANN: ok, UBERON:0001626
name: left coronary artery

931676 --> all UBERON annotation about aorta
--> ANN: ok, UBERON:0001496 - ascending aorta

for kidney, finally we map on? --> meaning do we keep laterality or not. 
---> ANN: regarding (last ;-)  Fred's comments, we annotate on
UBERON:0000082 adult mammalian kidney
we cannot keep cortex for reasons that there are medulla also present in the samples

1272905, 1268124, 1267928 --> how can frontal cortex be mixed with cerebellum?? --> by precaution eliminate samples?
--->ANN: I guess, we can consider info from column SMSMPSTE and annotate as you did (for example, UBERON:0014890 right hemisphere of cerebellum  when said 'Right Cerebellum'). The issue is due to the fact there are 2 targets for brain, Right cerebral frontal pole cortex and cerebellum
see 
http://biospecimens.cancer.gov/resources/sops/docs/GTEx_SOPs/BBRB-PR-0004-W1%20GTEx%20Tissue%20Harvesting%20Work%20Instruction.pdf

1267896 --> better to leave on frontal cortex, or to annotate on prefrontal cortex?
---> ANN: 'Left prefrontal cortex' ok to annotate on UBERON:0000451 - prefrontal cortex

**Comment by mimiblis** [comment]
Thanks Anne
