### ISSUE TITLE
GTEX-->to RNAseq file

### ISSUE THREAD

**Issue by mimiblis** [BgeeDB/expression-annotations#79]
I have made a branch called GTEX_to_RNAseq.
So Amina and I will be able to fill the RNAseq file
  - Amina from the beginning to line 2990 (in selected-samples) + stats
  - Angel from line 2991 to the end (in selected-samples)

CAUTION: see #75, there are still some things to correct!

**Comment by mimiblis** [comment]
--> what do we enter in ChipID?

**Comment by fbastian** [comment]
Where is the 'youpilala' branch? :p

**Comment by mimiblis** [comment]
I thought it might be à little clearer like this

**Comment by ANiknejad** [comment]
pour les annotations, prenez l'id SAMPID, et Sébastien va gérer via le fichier
SraRunTable_SRA_data_10-07-2015.txt


voir mon mail du jeudi 26 novembre:
SraRunTable_SRA_data_10-07-2015.txt
les samples GTEx sont dispo ci-dessous
http://www.ebi.ac.uk/ena/data/view/PRJNA75899

**Comment by mimiblis** [comment]
Ça marche oui

**Comment by ANiknejad** [comment]
question: quelle(s) colonne(s) avez-vous considérer pour reporter l'info Bgee colonne 'infoOrgan'?

Idem pour 'infoStage'

Merci!

**Comment by mimiblis** [comment]
selon le fichier selected-samples:
infoOrgan --> colonne F = SMTSD
infoStage --> colonne P = age (int)

**Comment by mimiblis** [comment]
concernant ma partie, j'ai terminé, et j'ai aussi fait le check des réplicats...

**Comment by ANiknejad** [comment]
merci de donner le nom original des colonnes telles que affiché dans le fichier original (colonne D=?)

**Comment by mimiblis** [comment]
désolée :-/ c'est fait

**Comment by ANiknejad** [comment]
In RNASeqLibrary.tsv

GTEX-Y114-2126-SM-4TT8B 
is reported with 
'skin of abdomen'
for Bgee column 'infoOrgan' while the original GTEx file only provides these information:
Skin just above pubic hair	Skin	Skin - Not Sun Exposed (Suprapubic)	

WE CAN NOT DISPLAY SUCH INFORMATION in column 'infoOrgan', because this column is here to display the original information (copy/paste) the annotator used to do annotation.

I agree, in GTEx file they provided the Uberon term (skin of abdomen) too, but we re-annotate GTEx and then we provide the reasons of our annotation.

I agree too, original information about sample type is spread in many columns
SMPTHNTS	SMSMPSTE	SMTS	SMTSD	SMTSC

so how to manage that?????

**Comment by mimiblis** [comment]
oh... so that would be a BIG problem for many organs :-/
by the way, is PRJNA75899 correct for experiment ID?

**Comment by ANiknejad** [comment]
No, please use SRP012682
right, @smoretti ?

http://www.ebi.ac.uk/ena/data/view/SRP012682

**Comment by smoretti** [comment]
Yes, right

**Comment by ANiknejad** [comment]
in RNASeqLibrary.tsv
could you please check
GTEX-U3ZN-0726-SM-4DXT5 

infoOrgan appears like
Uterus â€“ corpus

**Comment by fbastian** [comment]
@mimiblis @aechchiki @ANiknejad: Can I delete the branch 'GTEX_to_RNAseq'?
There is a bunch of commits from @mimiblis not merged in master, see https://github.com/BgeeDB/expression-annotations/compare/GTEX_to_RNAseq
